from pathlib import Path

root = Path(__file__).resolve().parent
source = (root / 'concept.html').read_text(encoding='utf-8')
addition = '''
<section id="demo-plan"><div class="eyebrow">19 / 확정 시연 기획</div><h2>네 가지 장소, 서로 다른 위험.<br>하나의 학습·관제 시스템.</h2><p class="lead">① AWS 행사장 ② 야구장 ③ 공연장 ④ 미국 학교의 총기 위협 상황을 시연 대상으로 설정합니다. 각 장소에서 사람과 환경을 바꾸고, 위험 세계를 찾아 개선 전후를 비교한 뒤 관리자 승인 기반의 대응까지 연결합니다.</p><p>네 시연 모두 제품 범위에 포함합니다. AWS 행사장을 실제 현장 검증의 기준 사례로 삼고, 나머지는 확보한 자료에 따라 재구성 또는 가상 공간으로 표시합니다. 실제 사고를 재현하거나 특정 시설의 안전성을 보증하는 시연은 아닙니다.</p></section>
<section><div class="eyebrow">DEMO 01 / AWS 행사장</div><h2>오늘 우리가 있는 공간을 먼저 검토합니다.</h2><div class="grid"><div class="card human"><h3>입력과 변화</h3><ul><li>확보 예정인 현장 사진·영상·도면, 실제 사용 가능한 출구와 통로, 좌석·부스 배치.</li><li>예상 인원과 행사 일정, 직원 배치, 현재 대응 매뉴얼.</li><li>공간에 익숙한 참가자와 처음 온 참가자, 이동 속도·반응 시간·동행 여부가 다른 집단.</li><li>화재·연기 후보 발생, 출구 일부 사용 불가, 행사 종료 시 동시 이동 등의 트리거.</li></ul></div><div class="card environment"><h3>보여줄 결과</h3><p>어느 통로에서 병목이 생기는지, 어떤 참가자의 이동이 늦어지는지, 기존 매뉴얼에 해당 상황의 안내가 있는지 확인합니다.</p><p><strong>개선 비교:</strong> 사용 가능한 출구 운영, 장애물 제거, 안내 인력 배치, 구역별 이동 순서 변경 전후를 같은 조건에서 비교합니다.</p><p><strong>실시간 연결:</strong> 시험 영상/카메라 화재 후보 → 근거 화면 → 관리자 승인 → 모의 현장 연락 → 처리 기록.</p></div></div><p class="muted">현장 자료는 확보 후 Git에 올릴 예정입니다. 현재 확보 완료로 표시하지 않습니다. 대용량 영상은 Git LFS 또는 접근 가능한 별도 저장소 링크로 연결하고, 자료 버전·촬영 시점·실측 여부를 기록합니다. 행사 관계자의 결과 검토도 예정 단계입니다.</p></section>
<section><div class="eyebrow">DEMO 02 / 야구장</div><h2>큰 공간에서도 사람은 좁은 곳에 모입니다.</h2><div class="grid"><div class="card human"><h3>입력과 변화</h3><ul><li>관람석 구역, 계단, 출입구, 매점·복도와 집결 공간.</li><li>가족·동행 집단, 공간 익숙함, 이동 지원 필요성, 구역별 관람객 구성.</li><li>경기 종료 동시 이동, 특정 출구 폐쇄, 일부 구역 연기, 우천에 따른 이동 변화.</li></ul></div><div class="card environment"><h3>관찰·개선·관제</h3><p><strong>관찰:</strong> 구역별 이동 완료 시간, 계단·복도 병목, 서로 반대 방향으로 이동하는 흐름의 충돌.</p><p><strong>개선:</strong> 구역별 순차 퇴장, 안내 인력 재배치, 통로 운영 변경을 비교합니다. 다른 위험 구역으로 혼잡을 옮겼는지도 확인합니다.</p><p><strong>관제:</strong> 구역별 혼잡 후보와 위험 감지 → 관리자 검토 → 승인된 구역 안내·요원 연락 → 결과 기록.</p></div></div><p class="muted">초기에는 관람석 일부와 연결 통로부터 모델링하고 구역 수를 확대합니다. 전체 야구장의 실제 수용 능력이나 밀집 위험 기준은 입력 자료와 검증 범위를 명시합니다.</p></section>
<section><div class="eyebrow">DEMO 03 / 공연장</div><h2>어두움·소음·동행 행동이 겹치는 공간</h2><div class="grid"><div class="card human"><h3>입력과 변화</h3><ul><li>좌석형/스탠딩 구역, 무대, 펜스, 출구와 통로.</li><li>동행자를 기다리거나 찾는 집단, 안내 인지 시간과 이동 속도가 다른 참가자.</li><li>공연 종료, 정전, 화재·연기 후보, 특정 구역 이동 불가, 안내 전달 지연.</li></ul></div><div class="card environment"><h3>관찰·개선·관제</h3><p><strong>관찰:</strong> 안내를 늦게 인지한 집단, 출구 쏠림, 합류 지점과 좁은 통로의 혼잡.</p><p><strong>개선:</strong> 구역별 안내, 통로 확보, 안내 인력과 집결 방식 변경 전후를 비교합니다.</p><p><strong>관제:</strong> 화재·낙상·혼잡 후보 → 영상 근거와 위치 → 관리자 승인 → 구역 안내·의료/운영 담당 연락.</p></div></div><p class="muted">스탠딩 군중의 압력과 부상 추정은 단순 이동 모델만으로 검증되지 않습니다. 초기 화면은 혼잡·지연·미대피 지표를 중심으로 보여주고 위해 추정은 별도 모델 검증 이후 다룹니다.</p></section>
<section><div class="eyebrow">DEMO 04 / 미국 학교 · 총기 위협</div><h2>위협 감지와 승인된 보호 절차의 연결</h2><div class="grid"><div class="card human"><h3>입력과 변화</h3><ul><li>가상 학교의 교실·복도·출입구, 구역별 재실 인원과 담당자 역할.</li><li>교직원·학생 역할, 공간 익숙함, 안내 인지·도움 필요성의 차이.</li><li>총기 의심 물체 감지, 특정 구역 위협 보고, 이동 경로 사용 제한, 통신 지연.</li></ul></div><div class="card environment"><h3>관찰·개선·관제</h3><p><strong>관찰:</strong> 위협 확인과 통보 지연, 매뉴얼 미정의 구역, 담당자 미응답, 위험 구역으로 이어지는 안내 여부.</p><p><strong>개선:</strong> 연락 체계, 구역별 책임자, 승인·전달 절차의 누락을 보완하고 다시 시험합니다.</p><p><strong>관제:</strong> 총기 후보 영상 → 관리자·보안 담당 확인 → 승인된 보호 절차와 모의 통보 → 수신·조치 확인.</p></div></div><p class="muted">실제 학생 개인정보와 실제 학교의 취약 지점은 사용하지 않는 가상 시연을 기본으로 합니다. 실제 학교에 적용할 때는 해당 기관이 승인한 현지 매뉴얼을 입력받습니다. 총기 위협을 화재와 같은 일괄 대피로 처리하지 않으며, 공격 경로나 공격 최적화는 생성하지 않습니다. 실제 긴급기관 연락은 시연에 포함하지 않습니다.</p></section>
<section><div class="eyebrow">20 / 모든 시연의 공통 화면 흐름</div><h2>조건 입력부터 조치 결과까지 한 이야기로</h2><div class="flow"><div class="step"><b>화면 1</b><strong>장소·요청 입력</strong><p>인원과 페르소나, 자료 버전, 매뉴얼, 실험 요청</p></div><div class="step"><b>화면 2</b><strong>세계 생성·실행</strong><p>AI 설정 제안, 제약 확인, 실제 실행 수와 진행 상태</p></div><div class="step"><b>화면 3</b><strong>위험 세계 탐색</strong><p>긴급성·현실성·심각도·근거별 정렬과 타임라인 재생</p></div><div class="step"><b>화면 4</b><strong>개선·현장 대응</strong><p>매뉴얼 변경 전후, 실시간 감지, 승인·모의 실행·기록</p></div></div><p>결과 카드에는 ‘관측된 현상 → 원인 가설 → 근거 이벤트 → 매뉴얼 부족점 → 권장 조치 → 재실험 결과’를 같은 순서로 표시합니다. 세계 목록에서는 피해가 큰 경우뿐 아니라 근거가 부족해 추가 검증이 필요한 경우도 분리합니다.</p><p><strong>실행 수 표시:</strong> 생성한 조건 수, 실제 완료한 시뮬레이션 수, 실패·취소 수, 재생 가능한 세계 수를 구분합니다. 미리 계산한 결과와 현장에서 새로 실행한 결과도 구분합니다.</p></section>
<section><div class="eyebrow">21 / 추가로 탐색할 수 있는 것</div><h2>장소를 늘리기 전에, 네 장소의 검증 깊이를 높입니다.</h2><div class="grid"><div class="card"><h3>우선 추가할 공통 실험</h3><ul><li><strong>수용 인원 비교:</strong> 인원을 단계적으로 바꾸고 어느 조건에서 병목이 커지는지 비교.</li><li><strong>복합 사건:</strong> 화재와 정전, 출구 제한과 통보 지연 등 조합을 비교.</li><li><strong>안내 실패:</strong> 방송 미인지·담당자 미응답·네트워크 단절 시 대체 절차 시험.</li><li><strong>접근성:</strong> 이동 지원이 필요한 집단과 동행 집단이 안내에서 누락되는지 확인.</li><li><strong>불확실성:</strong> 행동 가정과 시드를 바꾸었을 때 개선안이 일관되게 유효한지 확인.</li></ul></div><div class="card"><h3>관제와 연결할 발전 기능</h3><ul><li><strong>현재 상태 재실험:</strong> 확인된 출구 상태·구역 인원을 반영해 재평가. 연산 지연과 정보의 최신성을 표시.</li><li><strong>매뉴얼 비교:</strong> 기존안과 변경안의 통보·승인·조치 완료 시간을 비교.</li><li><strong>담당자 미응답:</strong> 승인된 연락 순서에 따라 다음 담당자에게 전달할 제안 생성.</li><li><strong>안부 확인:</strong> 등록 참가자의 대피 완료·도움 요청·미응답 상태를 구분.</li><li><strong>행사 후 복기:</strong> 감지·승인·조치 로그를 시뮬레이션 기록과 비교해 다음 행사에 반영.</li></ul></div></div><p>추가 장소 후보는 지하철·환승역, 전시장, 대형 쇼핑몰, 지역 축제입니다. 초기 네 시연의 연결과 검증이 끝난 뒤 우선순위를 결정합니다.</p></section>
<section><div class="eyebrow">22 / 자료 확보와 완료 기준</div><h2>자료가 들어오면 구현 범위를 확정합니다.</h2><div class="card"><ul><li><strong>자료:</strong> 장소별 공간 구조·치수·출구 상태, 구역별 예상 인원, 일정·배치, 대응 매뉴얼, 카메라 구역.</li><li><strong>출처:</strong> 실제 현장/공개 도면/가상 구조를 구분하고 파일·출처·날짜·사용 범위를 기록.</li><li><strong>시뮬레이션:</strong> 동일 조건 재현, 이동 경로 유효성, 개선 전후 비교, 세계별 로그 보존.</li><li><strong>관제:</strong> 탐지 누락·오경보, 카메라에서 화면까지 지연, 관리자 승인, 모의 연락 성공·실패·중복 방지.</li><li><strong>시연 완료:</strong> 네 장소마다 최소 하나의 위험 사례와 개선 비교가 실제 결과로 연결되고, 실행되지 않은 기능은 기획 또는 모의 화면으로 표시.</li><li><strong>대규모 확장:</strong> 단일 세계의 실행 시간·메모리를 측정한 뒤 수천·수만 회의 실행 비용과 병렬 작업 수를 산정.</li></ul><p>피해 감소율, 실제 발생 확률, 실제 시설의 안전 등급은 검증 없이 만들어내지 않습니다. 장소별 수치가 없을 때는 계산 전으로 표시합니다.</p></div></section>
<section><div class="eyebrow">23 / 4분 발표 구성 제안</div><h2>AWS에서 깊게, 세 장소에서 확장성을</h2><div class="card"><p><strong>0:00–0:30</strong> “모든 안전수칙은 피로 쓰인다”와 사후 대응의 한계.</p><p><strong>0:30–1:45</strong> AWS 행사장 입력 → 다양한 세계 → 위험 사례와 개선 비교. 실제 실행 수와 근거 표시.</p><p><strong>1:45–2:20</strong> 야구장·공연장·미국 학교에서 사람·위험·매뉴얼이 어떻게 달라지는지 대표 세계로 설명.</p><p><strong>2:20–3:15</strong> 실시간 감지 → 관리자 승인 → 모의 매뉴얼 실행 → 기억과 개선으로 연결.</p><p><strong>3:15–4:00</strong> 테스트와 실패·개선, 행사 관계자 피드백의 실제 확보 여부, 도입 가치, Codex로 구현·검토한 과정.</p><p class="muted">이 시간표는 발표 설계안입니다. 네 장소를 모두 깊게 설명하기보다 대표 사례와 확장 사례를 연결합니다. 대본의 감정적 후킹과 PPT의 짧은 문구는 별도로 작성합니다.</p></div></section>
'''
overview = '''<section><div class="eyebrow">제품의 전체 구조</div><h2>수천·수만 개의 세계에서 배우고,<br>현장 대응을 계속 발전시킵니다.</h2><div class="card"><p>AI는 행사 정보와 사용자 요청을 해석해 인원수·페르소나·사건 위치·시점·운영 조건을 제안합니다. 물리적 제약과 설정 근거를 검토한 뒤 세계를 실행하고 ID·랜덤 시드·모델·매뉴얼 버전을 기록합니다. 수천·수만 회는 처리량 검증 후 확장할 목표이며 현재 완료 수치가 아닙니다.</p><p>페르소나는 AI가 설정하거나 실제 행사 집계 정보를 반영합니다. NVIDIA의 <a href="https://huggingface.co/datasets/nvidia/Nemotron-Personas-Korea" style="color:var(--mint)">Nemotron-Personas-Korea 공식 자료</a>도 합성 프로필 후보입니다. 재난 시 이동·반응 행동은 별도로 모델링하고 검증해야 합니다. 아직 연동 완료한 자료는 아닙니다.</p><p>세계마다 위험이 시작되고 확산하는 과정, 미대피·혼잡·지연, 기존 매뉴얼의 누락과 충돌을 기록합니다. Agent는 근거 로그에서 원인 가설과 개선안을 제안하고, 같은 조건의 개선 전후 재실험으로 확인합니다. 세계 목록은 긴급성·심각도·현실성·근거 수준으로 정렬합니다. AI의 현실성 평가는 실제 발생 확률과 구분합니다.</p><p>LLM Wiki 또는 온톨로지 메모리는 조건·사건·대응·결과를 연결합니다. 관리자 승인 후 갱신된 매뉴얼을 다시 시험하고 운영에 반영합니다. 실시간 관제는 카메라 감지 → 상황 정리 → 관리자 승인 → 매뉴얼 실행 → 결과 확인으로 이어집니다.</p><p>화재 시 신고 지원, 총기 후보 감지 시 보안 담당 연락, 혼잡을 반영한 경로 분배, 등록 참가자의 참석·대피 완료·도움 요청 확인으로 확장합니다. 외부 연락·대피 안내는 관리자 승인 후 실행하며 미응답은 상태 미확인으로 구분합니다. 시연의 외부 연락은 모의 실행입니다. 현장 기록은 다음 시뮬레이션과 관제 개선의 근거가 됩니다.</p></div></section>'''
addition = addition.replace('19 /', '07 /').replace('20 /', '08 /').replace('21 /', '09 /').replace('22 /', '10 /').replace('23 /', '11 /')
vision = '''<section id="vision-plan"><div class="eyebrow">12 / 실시간 감지 구현 계획</div><h2>화재는 YOLO,<br>낙상은 자세와 시간의 변화로 판단합니다.</h2><p>AI Hub에서 받은 원본과 라벨을 학습·평가에 활용합니다. 행사 카메라 영상에서 위험 후보를 찾고, 위치·시각·근거 화면을 하나의 관제 이벤트로 전달합니다. 영상 인식 모델은 위험 후보를 만들고 Agent는 승인된 매뉴얼을 연결합니다.</p><div class="grid"><article class="card human"><h3>화재·연기 · YOLO</h3><p><strong>구성:</strong> AI Hub 화재·연기 이미지와 라벨 → YOLO 미세조정 → 영상의 불·연기 후보 위치와 점수 → 관제 이벤트.</p><p>정상 장면과 화재처럼 보이는 유사 장면을 함께 평가합니다. 반복 프레임에서 경보가 지속되는지 확인하고, 같은 카메라의 중복 경보를 묶는 방식을 시험합니다.</p><p><strong>현재:</strong> NHN 학습과 맥미니 추론을 확인했습니다. 오경보·누락이 남아 있으며 실제 행사장 카메라 성능은 별도 검증 대상입니다.</p></article><article class="card environment"><h3>낙상 · MediaPipe + 별도 분류기</h3><p><strong>계획:</strong> AI Hub 영상·행동 구간 라벨 → MediaPipe Pose Landmarker로 관절 추출 → 동일 인물의 연속 자세 특징 → 낙상 분류 → 관제 이벤트.</p><p>몸통 기울기, 골반 높이 변화, 하강 속도, 쓰러진 자세의 지속시간 등을 특징 후보로 사용합니다. 초기에는 특징 기반 분류기로 비교하고, 데이터와 성능에 따라 LSTM·TCN 등 시간 모델을 검토합니다.</p><p><strong>현재:</strong> 실제 초기 시험은 YOLO11n-pose와 간단한 로지스틱 분류기로 진행했습니다. MediaPipe 전환·학습·성능 비교는 아직 수행 전입니다.</p></article></div><div class="card" style="margin-top:20px"><h3>MediaPipe의 역할과 실패 처리</h3><p>Pose Landmarker는 신체의 33개 관절 위치를 추출하는 도구이며 그 자체가 완성된 낙상 탐지기는 아닙니다. 사람별 추적, 관절 품질 확인, 시간 구간 판정이 별도로 필요합니다. 여러 사람의 관절을 한 사람의 움직임처럼 합치지 않습니다.</p><p>앉기·숙이기·눕기와 실제 낙상을 구분하고, 사람이나 관절이 충분히 보이지 않으면 ‘정상’이 아니라 ‘판단 보류’로 기록합니다. 기존 시험에서 나타난 작은 사람·가림·대상자 누락을 우선 검증합니다. MediaPipe가 기존 방식보다 더 정확하다고 미리 가정하지 않습니다.</p><p class="caption">기술 출처: <a href="https://developers.google.com/edge/mediapipe/solutions/vision/pose_landmarker/python" style="color:var(--mint)">Google 공식 Pose Landmarker Python 가이드</a>.</p></div></section><section><div class="eyebrow">13 / 학습·평가·운영 연결</div><h2>NHN에서 학습하고, 맥미니에서 실제 입력으로 검증합니다.</h2><div class="flow"><div class="step"><b>데이터</b><strong>원본·라벨 정리</strong><p>영상 ID 단위 분리, 정상·위험 구간 확인, 라벨 범위 점검</p></div><div class="step"><b>학습</b><strong>NHN 실험</strong><p>YOLO 미세조정 또는 자세 특징 기반 낙상 분류기 학습</p></div><div class="step"><b>평가</b><strong>분리한 영상 시험</strong><p>탐지·누락·오경보·판단 보류·경보 지연을 함께 기록</p></div><div class="step"><b>운영 시험</b><strong>맥미니 관제 연결</strong><p>실제 카메라 해상도와 동시 입력 수에서 지연·부하 확인</p></div></div><p>MediaPipe는 전처리·추론 환경이고 별도 낙상 분류기를 학습합니다. GPU 서버를 쓴다고 MediaPipe 단계가 자동으로 GPU 가속되는 것은 아닙니다. 맥미니의 MediaPipe 실행 가능 여부와 성능도 새로 확인합니다.</p><p>총기 감지는 별도 데이터·전용 가중치·평가가 필요한 YOLO 후보 기능입니다. 화재 모델의 성공을 총기 감지 성능으로 해석하지 않습니다. 기존 기본 모델만으로 총기 탐지가 된다고 표시하지 않습니다.</p><div class="statement">위험 후보 감지 → 근거·위치 표시 → 관리자 승인<br>→ 승인된 연락·안내 → 수신·조치 결과 기록</div><p>개발 하네스와 개발 에이전트는 OpenAI 모델만 사용합니다. 제품의 비전 기능에는 사용자가 허용한 YOLO·MediaPipe를 사용합니다. 외부 연락과 대피 안내의 관리자 승인 원칙은 유지합니다.</p></section>'''
vision = vision.replace('MediaPipe + 별도 분류기', 'YOLO Pose + 별도 분류기').replace('MediaPipe Pose Landmarker로 관절 추출', 'YOLO11n-pose로 관절 추출').replace('MediaPipe 전환·학습·성능 비교는 아직 수행 전입니다.', '기존 YOLO Pose 경로를 유지하고 사람 추적·시간 특징·낙상 분류 성능을 개선합니다.').replace('MediaPipe의 역할과 실패 처리', 'YOLO Pose의 역할과 실패 처리').replace('Pose Landmarker는 신체의 33개 관절 위치를 추출하는 도구이며', 'YOLO11n-pose는 신체 관절 위치를 추출하는 모델이며').replace('MediaPipe가 기존 방식보다 더 정확하다고 미리 가정하지 않습니다.', '자세 추출 성공을 낙상 감지 성공으로 해석하지 않습니다.').replace('기술 출처: <a href="https://developers.google.com/edge/mediapipe/solutions/vision/pose_landmarker/python" style="color:var(--mint)">Google 공식 Pose Landmarker Python 가이드</a>.', '데이터 출처: <a href="https://aihub.or.kr/aihubdata/data/view.do?dataSetSn=167" style="color:var(--mint)">AI Hub 시니어 이상행동 영상</a>. 데이터 라벨과 별도로 자세 추출 및 낙상 분류 파이프라인을 구성합니다.').replace('MediaPipe는 전처리·추론 환경이고 별도 낙상 분류기를 학습합니다. GPU 서버를 쓴다고 MediaPipe 단계가 자동으로 GPU 가속되는 것은 아닙니다. 맥미니의 MediaPipe 실행 가능 여부와 성능도 새로 확인합니다.', 'YOLO Pose가 추출한 관절 특징으로 별도 낙상 분류기를 학습합니다. 영상 ID별 학습·검증 분리를 유지하고, 다인 장면의 사건 당사자 추적과 맥미니의 실제 입력 부하를 검증합니다.').replace('사용자가 허용한 YOLO·MediaPipe를 사용합니다.', '사용자가 허용한 YOLO 계열 모델을 사용합니다. 낙상의 현재 선택은 YOLO Pose이며 MediaPipe는 채택하지 않습니다.')
source = source.replace('<footer>', overview + addition + vision + '<footer>', 1)
source = source.replace('기획 초안 v0.2', '기획 초안 v0.3').replace('기획서 v0.2', '기획서 v0.3')
(root / '기획서.html').write_text(source, encoding='utf-8')
print('기획서.html created')
