// Generated by device/generate-assets.mjs; edit device/alerts.json instead.
#ifndef CG_CATALOG_H
#define CG_CATALOG_H
typedef struct { const char *before; const char *emphasis; const char *after; } cg_instruction_line_t;
typedef struct { const char *title; cg_instruction_line_t lines[2]; unsigned line_count; unsigned severity; } cg_alert_text_t;
static const cg_alert_text_t cg_alerts[] = {
    {"수신된 경고 없음", {{"현장 상황을 계속 확인해 주세요.", "", ""}, {"", "", ""}}, 1, 0},
    {"출입구 통제", {{"", "통제된 출입구를 피해", ""}, {"운영요원의 안내를 따라 주세요.", "", ""}}, 2, 1},
    {"이동 정체 주의", {{"", "앞사람과 간격을 유지", "하고"}, {"운영요원의 안내를 따라 주세요.", "", ""}}, 2, 1},
    {"이동 경로 확인", {{"이동을 서두르지 말고", "", ""}, {"", "운영요원의 안내를 기다려 주세요.", ""}}, 2, 1},
    {"모든 출입구 통제", {{"운영요원은 출입구 상태를", "", ""}, {"", "즉시 확인해 주세요.", ""}}, 2, 2},
    {"낙상 의심 알림", {{"", "주변 공간을 확보", "하고"}, {"운영요원에게 알려 주세요.", "", ""}}, 2, 2},
    {"응급 도움 요청", {{"운영요원은 현장을 확인하고", "", ""}, {"", "응급 지원을 요청해 주세요.", ""}}, 2, 2},
    {"화재 의심 경고", {{"현장을 확인하고", "", ""}, {"", "대피 안내에 따라 주세요.", ""}}, 2, 2},
    {"위험 물체 의심", {{"", "접근하지 말고", ""}, {"현장 보안요원에게 알려 주세요.", "", ""}}, 2, 2},
};
static const char *cg_zones[] = {"행사장 전체", "A 출입구 · 서측", "B 출입구 · 중앙", "C 출입구 · 동측"};
static const char *cg_sources[] = {"시뮬레이션", "시험 경고"};
#define CG_BRAND "JEONJO"
#define CG_WAITING "관제 연결 대기"
#define CG_STALE "연결 끊김 · 마지막 안내"
#define CG_LIVE "관제 수신 중"
#define CG_ACK "안내 확인"
#define CG_ACKED "확인됨 · 상황 해제 대기"
#define CG_WARNING "주의 안내"
#define CG_CRITICAL "위험 경고"
#define CG_NORMAL "관제 안내"
#define CG_COUNT "전체 경고"
#define CG_UNIT "건"
#define CG_COLOR_BACKGROUND 0x000000
#define CG_COLOR_TEXT 0xFFFFFF
#define CG_COLOR_CRITICAL 0xFF0000
#define CG_COLOR_WARNING 0xFFFF00
#define CG_COLOR_NORMAL 0x00FF00
#define CG_COLOR_WAITING 0x00CFFF
#endif
