// Generated by device/generate-assets.mjs; edit device/pictograms.json instead.
#ifndef CG_PICTOGRAMS_H
#define CG_PICTOGRAMS_H
#include "lvgl.h"
#define CG_ICON_SIZE 56
#define CG_ICON_WAITING 9
typedef struct { const lv_point_precise_t *points; unsigned count; } cg_icon_line_t;
typedef struct { int x, y, diameter; } cg_icon_circle_t;
typedef struct { const char *id; const cg_icon_line_t *lines; unsigned line_count; const cg_icon_circle_t *circles; unsigned circle_count; } cg_icon_t;
static const lv_point_precise_t cg_icon_clear_0[] = {{28,5},{49,14},{47,33},{40,44},{28,51},{16,44},{9,33},{7,14},{28,5}};
static const lv_point_precise_t cg_icon_clear_1[] = {{16,28},{23,35},{40,19}};
static const cg_icon_line_t cg_icon_clear_lines[] = {{cg_icon_clear_0,9},{cg_icon_clear_1,3}};
static const lv_point_precise_t cg_icon_exit_closed_0[] = {{12,51},{12,5},{44,5},{44,51}};
static const lv_point_precise_t cg_icon_exit_closed_1[] = {{5,51},{51,51}};
static const lv_point_precise_t cg_icon_exit_closed_2[] = {{21,28},{35,28}};
static const cg_icon_line_t cg_icon_exit_closed_lines[] = {{cg_icon_exit_closed_0,4},{cg_icon_exit_closed_1,2},{cg_icon_exit_closed_2,2}};
static const lv_point_precise_t cg_icon_congestion_0[] = {{16,51},{16,37},{21,30},{35,30},{40,37},{40,51}};
static const lv_point_precise_t cg_icon_congestion_1[] = {{5,42},{5,28},{9,23},{14,23}};
static const lv_point_precise_t cg_icon_congestion_2[] = {{51,42},{51,28},{47,23},{42,23}};
static const cg_icon_line_t cg_icon_congestion_lines[] = {{cg_icon_congestion_0,6},{cg_icon_congestion_1,4},{cg_icon_congestion_2,4}};
static const cg_icon_circle_t cg_icon_congestion_circles[] = {{21,7,14},{5,7,9},{42,7,9}};
static const lv_point_precise_t cg_icon_route_blocked_0[] = {{7,47},{7,28},{35,28}};
static const lv_point_precise_t cg_icon_route_blocked_1[] = {{26,19},{35,28},{26,37}};
static const lv_point_precise_t cg_icon_route_blocked_2[] = {{49,7},{49,49}};
static const lv_point_precise_t cg_icon_route_blocked_3[] = {{42,7},{51,7}};
static const lv_point_precise_t cg_icon_route_blocked_4[] = {{42,49},{51,49}};
static const cg_icon_line_t cg_icon_route_blocked_lines[] = {{cg_icon_route_blocked_0,3},{cg_icon_route_blocked_1,3},{cg_icon_route_blocked_2,2},{cg_icon_route_blocked_3,2},{cg_icon_route_blocked_4,2}};
static const lv_point_precise_t cg_icon_all_exits_closed_0[] = {{12,51},{12,5},{44,5},{44,51}};
static const lv_point_precise_t cg_icon_all_exits_closed_1[] = {{5,51},{51,51}};
static const lv_point_precise_t cg_icon_all_exits_closed_2[] = {{21,19},{35,33}};
static const lv_point_precise_t cg_icon_all_exits_closed_3[] = {{35,19},{21,33}};
static const cg_icon_line_t cg_icon_all_exits_closed_lines[] = {{cg_icon_all_exits_closed_0,4},{cg_icon_all_exits_closed_1,2},{cg_icon_all_exits_closed_2,2},{cg_icon_all_exits_closed_3,2}};
static const lv_point_precise_t cg_icon_fall_0[] = {{19,21},{28,30},{40,30},{47,40}};
static const lv_point_precise_t cg_icon_fall_1[] = {{28,30},{23,42},{12,42}};
static const lv_point_precise_t cg_icon_fall_2[] = {{23,26},{12,28},{7,21}};
static const lv_point_precise_t cg_icon_fall_3[] = {{23,26},{30,14},{40,12}};
static const lv_point_precise_t cg_icon_fall_4[] = {{5,51},{51,51}};
static const cg_icon_line_t cg_icon_fall_lines[] = {{cg_icon_fall_0,4},{cg_icon_fall_1,3},{cg_icon_fall_2,3},{cg_icon_fall_3,3},{cg_icon_fall_4,2}};
static const cg_icon_circle_t cg_icon_fall_circles[] = {{6,6,12}};
static const lv_point_precise_t cg_icon_medical_0[] = {{19,5},{37,5},{37,19},{51,19},{51,37},{37,37},{37,51},{19,51},{19,37},{5,37},{5,19},{19,19},{19,5}};
static const cg_icon_line_t cg_icon_medical_lines[] = {{cg_icon_medical_0,13}};
static const lv_point_precise_t cg_icon_fire_0[] = {{28,5},{30,16},{37,23},{42,16},{49,30},{49,37},{44,47},{35,51},{21,51},{12,47},{7,37},{7,30},{12,21},{16,28},{21,21},{28,5}};
static const lv_point_precise_t cg_icon_fire_1[] = {{28,30},{35,40},{35,47},{28,51},{21,47},{21,42},{28,30}};
static const cg_icon_line_t cg_icon_fire_lines[] = {{cg_icon_fire_0,16},{cg_icon_fire_1,7}};
static const lv_point_precise_t cg_icon_weapon_0[] = {{28,5},{49,14},{47,33},{40,44},{28,51},{16,44},{9,33},{7,14},{28,5}};
static const lv_point_precise_t cg_icon_weapon_1[] = {{28,16},{28,28}};
static const cg_icon_line_t cg_icon_weapon_lines[] = {{cg_icon_weapon_0,9},{cg_icon_weapon_1,2}};
static const cg_icon_circle_t cg_icon_weapon_circles[] = {{26,35,5}};
static const lv_point_precise_t cg_icon_waiting_0[] = {{7,19},{16,12},{28,9},{40,12},{49,19}};
static const lv_point_precise_t cg_icon_waiting_1[] = {{14,28},{21,23},{28,21},{35,23},{42,28}};
static const lv_point_precise_t cg_icon_waiting_2[] = {{21,37},{28,33},{35,37}};
static const cg_icon_line_t cg_icon_waiting_lines[] = {{cg_icon_waiting_0,5},{cg_icon_waiting_1,5},{cg_icon_waiting_2,3}};
static const cg_icon_circle_t cg_icon_waiting_circles[] = {{26,44,5}};
static const cg_icon_t cg_icons[] = {
    {"clear", cg_icon_clear_lines, 2, NULL, 0},
    {"exit_closed", cg_icon_exit_closed_lines, 3, NULL, 0},
    {"congestion", cg_icon_congestion_lines, 3, cg_icon_congestion_circles, 3},
    {"route_blocked", cg_icon_route_blocked_lines, 5, NULL, 0},
    {"all_exits_closed", cg_icon_all_exits_closed_lines, 4, NULL, 0},
    {"fall", cg_icon_fall_lines, 5, cg_icon_fall_circles, 1},
    {"medical", cg_icon_medical_lines, 1, NULL, 0},
    {"fire", cg_icon_fire_lines, 2, NULL, 0},
    {"weapon", cg_icon_weapon_lines, 2, cg_icon_weapon_circles, 1},
    {"waiting", cg_icon_waiting_lines, 3, cg_icon_waiting_circles, 1},
};
#endif
