// OpenAI Speech API → cached 24 kHz, signed little-endian PCM → firmware flash.
// Only fixed, reviewable phrases are sent. Keys never enter generated assets.
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadEnv } from 'vite';

const root = dirname(fileURLToPath(import.meta.url));
const catalog = JSON.parse(await readFile(resolve(root,'alerts.json'),'utf8'));
const model = 'gpt-4o-mini-tts-2025-12-15', voice = 'marin';
const instructions = '한국어 여성 안내 방송처럼 차분하고 또렷하게 말하세요. 긴박한 문구도 과장하거나 소리 지르지 마세요. 보통 속도로 읽으세요. 입력 문구를 정확하게 읽고 음악, 효과음, 추가 설명을 넣지 마세요.';
const phrases = [
  ...catalog.kinds.map(k=>({id:k.id,text:`${k.title}. ${k.instruction.replaceAll('\n',' ')}`})),
  ...['행사장 전체 안내입니다.','에이 출입구 서쪽입니다.','비 출입구 중앙입니다.','씨 출입구 동쪽입니다.'].map((text,i)=>({id:`zone_${i}`,text})),
  {id:'test',text:'시험 경고입니다. 전조의 AI 합성 음성 안내입니다.'},
  {id:'simulation',text:'시뮬레이션 경고입니다. 전조의 AI 합성 음성 안내입니다.'},
  {id:'stale',text:'전조 AI 음성 안내입니다. 관제 연결이 끊겼습니다. 마지막 경고와 현장 상황을 확인해 주세요.'},
  {id:'ready',text:'전조 AI 합성 음성 안내입니다. LED와 음성 경고 장치가 준비되었습니다.'},
  {id:'multiple',text:'다른 경고도 있습니다. 관제 화면을 함께 확인해 주세요.'},
];
const cache = resolve(root,'voice-cache'), generated = resolve(root,'esp32/generated');
await mkdir(cache,{recursive:true}); await mkdir(generated,{recursive:true});
const env = loadEnv('development',resolve(root,'..'),'OPENAI_');
const key = process.env.OPENAI_API_KEY || env.OPENAI_API_KEY;
const clips = [], manifest = [];
let offset = 0;
for (const phrase of phrases) {
  const payload = {model,voice,instructions,input:phrase.text,response_format:'pcm'};
  const hash = createHash('sha256').update(JSON.stringify(payload)).digest('hex');
  const path = resolve(cache,`${hash}.pcm`);
  let pcm;
  try { pcm = await readFile(path); } catch {
    if (!key) throw new Error('프로젝트 .env.local에 OPENAI_API_KEY가 필요합니다.');
    const response = await fetch('https://api.openai.com/v1/audio/speech', {
      method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},
      body:JSON.stringify(payload), signal:AbortSignal.timeout(90000),
    });
    if (!response.ok) throw new Error(`OpenAI 음성 생성 실패 (${response.status}). 키와 모델 접근 권한을 확인해 주세요.`);
    pcm = Buffer.from(await response.arrayBuffer());
    if (pcm.length < 4800 || pcm.length > 1440000 || pcm.length%2) throw new Error('음성 응답 길이가 올바르지 않습니다.');
    await writeFile(path,pcm);
  }
  if (pcm.length < 4800 || pcm.length > 1440000 || pcm.length%2) throw new Error(`음성 캐시 오류: ${phrase.id}`);
  // Cap peaks to 80% full scale without boosting quiet clips; leave headroom at the speaker.
  const normalized = Buffer.from(pcm);
  let peak = 1;
  for (let i=0;i<pcm.length;i+=2) peak=Math.max(peak,Math.abs(pcm.readInt16LE(i)));
  const gain = Math.min(1,26214/peak);
  for (let i=0;i<pcm.length;i+=2) normalized.writeInt16LE(Math.round(pcm.readInt16LE(i)*gain),i);
  clips.push(normalized);
  manifest.push({...phrase,offset,bytes:normalized.length,sha256:createHash('sha256').update(normalized).digest('hex')});
  offset += normalized.length;
  console.log(`${phrase.id}: ${(normalized.length/48000).toFixed(1)}초 준비`);
}
if (offset > 7*1024*1024) throw new Error('음성 자산이 펌웨어 공간을 초과합니다.');
await writeFile(resolve(generated,'voice.pcm'),Buffer.concat(clips));
await writeFile(resolve(generated,'voice-manifest.json'),JSON.stringify({model,voice,sampleRate:24000,clips:manifest},null,2)+'\n');
await writeFile(resolve(generated,'voice_index.h'),`// Generated by device/generate-voices.mjs. All offsets and lengths are bytes.\n#pragma once\n#include <stdint.h>\nstruct VoiceClip { uint32_t offset, length; };\nstatic const VoiceClip VOICE_CLIPS[] = {\n${manifest.map(x=>`    {${x.offset}, ${x.bytes}}, // ${x.id}`).join('\n')}\n};\n`);
console.log(`보드 내장 음성 ${phrases.length}개, ${(offset/1024/1024).toFixed(2)} MiB 준비 완료`);
