// Regenerate after changing alerts.json. Font license: public/fonts/OFL.txt.
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
const root = fileURLToPath(new URL('../', import.meta.url));
const catalog = JSON.parse(readFileSync(`${root}/device/alerts.json`, 'utf8'));
const pictograms = JSON.parse(readFileSync(`${root}/device/pictograms.json`, 'utf8'));
const quote = text => JSON.stringify(text);
const instructions = catalog.kinds.map(a => {
  if (a.emphasis && (a.emphasis.includes('\n') || a.instruction.split(a.emphasis).length !== 2)) {
    throw new Error(`${a.id}: 강조 문구가 본문 한 줄에 정확히 한 번 있어야 합니다.`);
  }
  const lines = a.instruction.split('\n');
  if (lines.length > 2) throw new Error(`${a.id}: 가로 LCD 행동 안내는 최대 두 줄입니다.`);
  return lines.map(line => {
    if (!a.emphasis || !line.includes(a.emphasis)) return [line, '', ''];
    const parts = line.split(a.emphasis);
    return [parts[0], a.emphasis, parts[1]];
  });
});
const header = [
  '// Generated by device/generate-assets.mjs; edit device/alerts.json instead.',
  '#ifndef CG_CATALOG_H', '#define CG_CATALOG_H',
  'typedef struct { const char *before; const char *emphasis; const char *after; } cg_instruction_line_t;',
  'typedef struct { const char *title; cg_instruction_line_t lines[2]; unsigned line_count; unsigned severity; } cg_alert_text_t;',
  'static const cg_alert_text_t cg_alerts[] = {',
  ...catalog.kinds.map((a, i) => {
    const lines = instructions[i];
    const padded = lines.length === 1 ? [...lines, ['', '', '']] : lines;
    return `    {${quote(a.title)}, {${padded.map(line => `{${line.map(quote).join(', ')}}`).join(', ')}}, ${lines.length}, ${['normal','warning','critical'].indexOf(a.severity)}},`;
  }),
  '};',
  `static const char *cg_zones[] = {${catalog.zones.map(quote).join(', ')}};`,
  `static const char *cg_sources[] = {${catalog.sources.map(quote).join(', ')}};`,
  ...Object.entries(catalog.labels).map(([key,value]) => `#define CG_${key.toUpperCase()} ${quote(value)}`),
  ...Object.entries(catalog.colors).map(([key,value]) => `#define CG_COLOR_${key.toUpperCase()} 0x${value.slice(1)}`),
  '#endif', '',
].join('\n');
writeFileSync(`${root}/device/firmware/include/cg_catalog.h`, header);
// One geometry source for the LCD's 56px LVGL strokes and the web's SVG preview.
const iconIds = [...catalog.kinds.map(a => a.id), 'waiting'];
const scale = value => Math.round(value * 56 / 24);
const iconHeader = [
  '// Generated by device/generate-assets.mjs; edit device/pictograms.json instead.',
  '#ifndef CG_PICTOGRAMS_H', '#define CG_PICTOGRAMS_H', '#include "lvgl.h"',
  '#define CG_ICON_SIZE 56', `#define CG_ICON_WAITING ${iconIds.length - 1}`,
  'typedef struct { const lv_point_precise_t *points; unsigned count; } cg_icon_line_t;',
  'typedef struct { int x, y, diameter; } cg_icon_circle_t;',
  'typedef struct { const char *id; const cg_icon_line_t *lines; unsigned line_count; const cg_icon_circle_t *circles; unsigned circle_count; } cg_icon_t;',
];
for (const id of iconIds) {
  const icon = pictograms[id];
  if (!icon) throw new Error(`${id}: 픽토그램이 없습니다.`);
  for (const [i, points] of icon.lines.entries()) {
    if (points.length < 2 || points.some(p => p.length !== 2 || p.some(v => !Number.isFinite(v) || v < 1 || v > 23))) throw new Error(`${id}: 픽토그램 좌표 오류`);
    iconHeader.push(`static const lv_point_precise_t cg_icon_${id}_${i}[] = {${points.map(([x,y]) => `{${scale(x)},${scale(y)}}`).join(',')}};`);
  }
  iconHeader.push(`static const cg_icon_line_t cg_icon_${id}_lines[] = {${icon.lines.map((p,i) => `{cg_icon_${id}_${i},${p.length}}`).join(',')}};`);
  if (icon.circles.length) iconHeader.push(`static const cg_icon_circle_t cg_icon_${id}_circles[] = {${icon.circles.map(([x,y,r]) => `{${scale(x-r)},${scale(y-r)},${scale(2*r)}}`).join(',')}};`);
}
iconHeader.push('static const cg_icon_t cg_icons[] = {', ...iconIds.map(id => {
  const icon = pictograms[id];
  return `    {${quote(id)}, cg_icon_${id}_lines, ${icon.lines.length}, ${icon.circles.length ? `cg_icon_${id}_circles` : 'NULL'}, ${icon.circles.length}},`;
}), '};', '#endif', '');
writeFileSync(`${root}/device/firmware/include/cg_pictograms.h`, iconHeader.join('\n'));
const allText = JSON.stringify(catalog) + 'USB / 115200';
const symbols = [...new Set([...allText].filter(c => c.codePointAt(0) >= 128))].join('');
const temp = mkdtempSync(join(tmpdir(), 'cg-font-'));
try {
const convert = spawnSync('uv', ['run','--no-project','--python','3.12','--with','fonttools[woff]==4.60.1','python','-c',
  'import sys; from fontTools.ttLib import TTFont; from fontTools.varLib.instancer import instantiateVariableFont\nfor weight in (400,800):\n f=instantiateVariableFont(TTFont(sys.argv[1]), {"wght":weight}); f.flavor=None; f.save(f"{sys.argv[2]}/Pretendard-{weight}.ttf")',
  `${root}/public/fonts/PretendardVariable.woff2`, temp], {stdio:'inherit'});
if (convert.status !== 0) throw new Error('가변 글꼴 굵기 고정 실패');
for (const [name, size, weight] of [['cg_font_20',20,400], ['cg_font_20_bold',20,800], ['cg_font_28',28,800]]) {
  const font = join(temp, `Pretendard-${weight}.ttf`);
  const result = spawnSync('npx', ['--yes','lv_font_conv@1.5.3','--font',font,
    '--size',String(size),'--bpp','4','--format','lvgl','--no-compress','--lv-font-name',name,
    '--range','0x20-0x7e','--symbols',symbols,'--output',`${root}/device/firmware/src/${name}.c`], {stdio:'inherit'});
  if (result.status !== 0) throw new Error('글꼴 생성 실패');
  const output = `${root}/device/firmware/src/${name}.c`;
  writeFileSync(output, readFileSync(output,'utf8').replace(/^ \* Opts:.*$/m,
    ` * Generated by device/generate-assets.mjs. Font: CG UI ${size}px weight ${weight} (Pretendard subset, SIL OFL 1.1).`).trimEnd() + '\n');
}
} finally { rmSync(temp, {recursive:true, force:true}); }
