// Regenerate after changing alerts.json. Font license: public/fonts/OFL.txt.
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
const root = fileURLToPath(new URL('../', import.meta.url));
const catalog = JSON.parse(readFileSync(`${root}/device/alerts.json`, 'utf8'));
const quote = text => JSON.stringify(text);
const header = [
  '// Generated by device/generate-assets.mjs; edit device/alerts.json instead.',
  '#ifndef CG_CATALOG_H', '#define CG_CATALOG_H',
  'typedef struct { const char *title; const char *instruction; unsigned severity; } cg_alert_text_t;',
  'static const cg_alert_text_t cg_alerts[] = {',
  ...catalog.kinds.map(a => `    {${quote(a.title)}, ${quote(a.instruction)}, ${['normal','warning','critical'].indexOf(a.severity)}},`),
  '};',
  `static const char *cg_zones[] = {${catalog.zones.map(quote).join(', ')}};`,
  `static const char *cg_sources[] = {${catalog.sources.map(quote).join(', ')}};`,
  ...Object.entries(catalog.labels).map(([key,value]) => `#define CG_${key.toUpperCase()} ${quote(value)}`),
  ...Object.entries(catalog.colors).map(([key,value]) => `#define CG_COLOR_${key.toUpperCase()} 0x${value.slice(1)}`),
  '#endif', '',
].join('\n');
writeFileSync(`${root}/device/firmware/include/cg_catalog.h`, header);
const allText = JSON.stringify(catalog) + 'USB / 115200';
const symbols = [...new Set([...allText].filter(c => c.codePointAt(0) >= 128))].join('');
const temp = mkdtempSync(join(tmpdir(), 'cg-font-'));
const font = join(temp, 'Pretendard.ttf');
const convert = spawnSync('uv', ['run','--no-project','--python','3.12','--with','fonttools[woff]==4.60.1','python','-c',
  'import sys; from fontTools.ttLib import TTFont; f=TTFont(sys.argv[1]); f.flavor=None; f.save(sys.argv[2])',
  `${root}/public/fonts/PretendardVariable.woff2`, font], {stdio:'inherit'});
if (convert.status !== 0) process.exit(convert.status ?? 1);
try {
for (const size of [20,28]) {
  const result = spawnSync('npx', ['--yes','lv_font_conv@1.5.3','--font',font,
    '--size',String(size),'--bpp','4','--format','lvgl','--no-compress','--lv-font-name',`cg_font_${size}`,
    '--range','0x20-0x7e','--symbols',symbols,'--output',`${root}/device/firmware/src/cg_font_${size}.c`], {stdio:'inherit'});
  if (result.status !== 0) throw new Error('글꼴 생성 실패');
  const output = `${root}/device/firmware/src/cg_font_${size}.c`;
  writeFileSync(output, readFileSync(output,'utf8').replace(/^ \* Opts:.*$/m,
    ` * Generated by device/generate-assets.mjs. Font: CG UI ${size}px (Pretendard subset, SIL OFL 1.1).`));
}
} finally { rmSync(temp, {recursive:true, force:true}); }
